### ISSUE TITLE
Supposition about the response while paginating

### ISSUE THREAD

**Issue by alfonso-higuera** [easybroker/easybroker_gem#10]
# What's the problem?

When using the `find_each` method of a `EasyBroker::PaginatedResponse` there
is a point in the code where it is supposed that the response has a `content` field
but this is not true for all resources.

In both the [staging](https://easybroker-staging.readme.io/reference/get_locations) and [production](https://dev.easybroker.com/reference/get_locations) playgrounds we can see that the response for
the `v1/locations` path doesn't have a `content` field in its JSON body.

## Output

```terminal
/Users/alfonso/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/easy_broker-1.0.4/lib/easy_broker/paginated_response.rb:42:in `each': undefined method `each' for nil (NoMethodError)

    response.content.each do |object|
                    ^^^^^
	from /Users/alfonso/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/easy_broker-1.0.4/lib/easy_broker/paginated_response.rb:32:in `block in find_each'
	from <internal:kernel>:187:in `loop'
	from /Users/alfonso/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/easy_broker-1.0.4/lib/easy_broker/paginated_response.rb:31:in `find_each'
	from properties.rb:13:in `<main>'
```

# Minimal, reproducible example

`script.rb`

```ruby
# frozen_string_literal: true

require 'easy_broker'

EasyBroker.configure do |config|
  config.api_key = 'l7u502p8v46ba3ppgvj5y2aad50lb9'
  config.api_root_url = EasyBroker::STAGING_API_ROOT_URL
  config.country_code = 'MX'
end

client = EasyBroker.client

client.locations.search.find_each do |location|
  puts location.inspect
end
```

`Gemfile`

```ruby
source 'https://rubygems.org'

gem 'easy_broker'
```

**Comment by alfonso-higuera** [comment]
⚠️  I just realized that the MRE above only works when the solution to #9 is already in place.
